Leong_Project/LeongGoodsApp/urls.py
from django.conf.urls import url
from . import views

urlpatterns = [
    url(r'^index/',views.index,name='index'),
    url(r'^list/(?P<gtype_id>[\d]+)/(?P<paging_id>[\d+]+)/$',views.list,name='list'),
    url(r'^detail/(?P<id>[\d]+)/$',views.detail,name='detail'),
    url(r'^cart/',views.cart,name='cart'),
]

Leong_Project/Leong_Project/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from UserApp import urls as User_urls
from LeongGoodsApp import urls as Good_urls
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    url(r'^admin/', include(admin.site.urls)),
    url(r'^user/',include(User_urls,namespace='user')),
    url(r'^goods/',include(Good_urls,namespace='main')),
    url(r'^ckeditor/', include('ckeditor_uploader.urls')),
]

urlpatterns += static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

Leong_Project/UserApp/urls.py
from django.conf.urls import url
from . import views

urlpatterns = [
    url(r'^register/', views.register, name='register'),
    url(r'^register_handle/', views.register_handle, name='register_handle'),
    url(r'^login/', views.login, name='login'),
    url(r'^loginhandle/',views.loginhandle,name='loginhandle')
]

Leong_Project/LeongGoodsApp/models.py
from django.db import models
from ckeditor_uploader.fields import RichTextUploadingField
import datetime


# Create your models here.

class TypeInfo(models.Model):
    """商品分类"""

    ttitle = models.CharField(max_length=20)
    isDelete = models.BooleanField(default=False)

    def __str__(self):
        return self.ttitle


class GoodsInfo(models.Model):
    """所有商品详情"""
    gtitle = models.CharField(max_length=23)  # 商品
    # gpic = models.ImageField(upload_to='static/media') # 图片
    isDelete = models.BooleanField(default=False)  # 删除
    gprice = models.DecimalField(max_digits=5, decimal_places=2)  # 价格

    gtype = models.ForeignKey(TypeInfo)  # 商品分类的外键关系

    gclick = models.IntegerField(default=0) # 点击量
    gunit = models.CharField(max_length=20, default='500g') # 商品重量
    gjianjie = models.TextField()
    gpub_date = models.DateTimeField(datetime.datetime.now()) #　时间
    gpubj_date = models.DateTimeField() # 时间
    gpic = RichTextUploadingField()

    def __str__(self):
        return self.gtitle

Leong_Project/UserApp/models.py
from django.db import models


# Create your models here.

# 创造用户注册所需的数据类型
class UserInfo(models.Model):
    uname = models.CharField(max_length=20)  # 姓名
    upwd = models.CharField(max_length=40)  # 密码
    uemail = models.CharField(max_length=30)  # 邮箱
    uaddress = models.CharField(max_length=100)  # 地址
    uphone = models.CharField(max_length=11)  # 手机
    ureceive = models.CharField(max_length=20)  # 收件人
    uzip_code = models.CharField(max_length=6)  # 邮编
    ugender = models.BooleanField(default=False)

Leong_Project/LeongGoodsApp/views.py
from django.shortcuts import render
from django.http import HttpResponse
from . import models
from django.core.paginator import Paginator


# Create your views here.
def index(request):
    pic = models.GoodsInfo.objects.filter(gtype_id=3)
    pi2 = models.GoodsInfo.objects.filter(gtype_id=4)
    content = {'pic': pic[:4], 'pic2': pi2}
    return render(request, 'index.html', content)


def list(request,gtype_id,paging_id):
    pic = models.GoodsInfo.objects.filter(gtype_id=gtype_id)
    pp = Paginator(pic,5)
    p = pp.page(int(paging_id))
    return render(request, 'list.html',{'gtype_id':gtype_id,'p':p})

def detail(request,id):
    a = models.GoodsInfo.objects.filter(id=id)
    return render(request,'detail.html',{'a':a})

def cart(request):
    return render(request,'cart.html')

Leong_Project/UserApp/views.py
from django.shortcuts import render, redirect
from django.http import HttpResponse
from . import models


# Create your views here.
# 返回一个注册页面
def register(request):
    return render(request, 'register.html')


# 处理用户输入的注册信息
def register_handle(request):
    uname1 = request.POST['user_name']
    upwd = request.POST['pwd']
    upwd2 = request.POST['cpwd']
    uemail1 = request.POST['email']

    try:
        uname = models.UserInfo.objects.get(uname=uname1)
        uemail = models.UserInfo.objects.get(uemail=uemail1)
        return HttpResponse('当前账号已经注册')
    except:
        if upwd == upwd2:
            user = models.UserInfo()
            user.uname = uname1
            user.upwd = upwd
            user.uemail = uemail1
            user.save()
            return render(request, 'login.html')


# 返回一个登录页面
def login(request):
    return render(request, 'login.html')


# 处理用户登录的信息
def loginhandle(request):
    uname = request.POST['username']
    upwd = request.POST['pwd']

    try:
        uname1 = models.UserInfo.objects.get(uname=uname)
        if upwd == uname1.upwd:
            return redirect('main:index')
    except:
        return HttpResponse('你的账号或者密码错误，请重新输入')

Leong_Project/templates/base.html
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en">
<head>
	<meta http-equiv="Content-Type" content="text/html;charset=UTF-8">
	<title>{% block title %}乐农优选-注册{% endblock %}</title>
	<link rel="stylesheet" type="text/css" href="/static/css/reset.css">
	<link rel="stylesheet" type="text/css" href="/static/css/main.css">
	<script type="text/javascript" src="/static/js/jquery-1.12.4.min.js"></script>
	{% block head %}{% endblock %}
</head>
<body>
    {% block body %}{% endblock %}
    <div class="footer no-mp">
		<div class="foot_link">
			<a href="#">关于我们</a>
			<span>|</span>
			<a href="#">联系我们</a>
			<span>|</span>
			<a href="#">招聘人才</a>
			<span>|</span>
			<a href="#">友情链接</a>
		</div>
		<p>CopyRight © 2016 乐农优选信息技术有限公司 All Rights Reserved</p>
		<p>电话：010-****888    京ICP备*******8号</p>
	</div>
</body>
</html>

Leong_Project/templates/base2.html
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN"
        "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en">
<head>
    <meta http-equiv="Content-Type" content="text/html;charset=UTF-8">
    <title>{% block title %}乐农优选-首页{% endblock %}</title>
    <link rel="stylesheet" type="text/css" href="/static/css/reset.css">
    <link rel="stylesheet" type="text/css" href="/static/css/main.css">
    <script type="text/javascript" src="/static/js/jquery-1.12.4.min.js"></script>
    <script type="text/javascript" src="/static/js/jquery-ui.min.js"></script>
    <script type="text/javascript" src="/static/js/slide.js"></script>
</head>
<body>
<div class="header_con">
    <div class="header">
        <div class="welcome fl">欢迎来到乐农优选!</div>
        <div class="fr">
            <div class="login_info fl">
                欢迎您：<em>张 山</em>
            </div>
            <div class="login_btn fl">
                <a href="{% url 'user:login' %}">登录</a>
                <span>|</span>
                <a href="{% url 'user:register' %}">注册</a>
            </div>
            <div class="user_link fl">
                <span>|</span>
                <a href="user_center_info.html">用户中心</a>
                <span>|</span>
                <a href="{% url 'main:cart' %}">我的购物车</a>
                <span>|</span>
                <a href="user_center_order.html">我的订单</a>
            </div>
        </div>
    </div>
</div>




{% block body %}
{% endblock %}


<div class="footer">
    <div class="foot_link">
        <a href="#">关于我们</a>
        <span>|</span>
        <a href="#">联系我们</a>
        <span>|</span>
        <a href="#">招聘人才</a>
        <span>|</span>
        <a href="#">友情链接</a>
    </div>
    <p>CopyRight © 2016 乐农优选技术有限公司 All Rights Reserved</p>
    <p>电话：010-****888 京ICP备*******8号</p>
</div>
<script type="text/javascript" src="/static/js/slide.js"></script>
<script type="text/javascript">
    BCSlideshow('focuspic');
    var oFruit = document.getElementById('fruit_more');
    var oShownum = document.getElementById('show_count');

    var hasorder = localStorage.getItem('order_finish');

    if (hasorder) {
        oShownum.innerHTML = '2';
    }

    oFruit.onclick = function () {
        window.location.href = 'list.html';
    }
</script>
</body>
</html>

Leong_Project/templates/index.html
{% extends 'base2.html' %}

{% block body %}
    <div class="search_bar clearfix">
    <a href="index.html" class="logo fl"><img src="/static/images/logo.png"></a>
    <div class="search_con fl">
        <input type="text" class="input_text fl" name="" placeholder="搜索商品">
        <input type="button" class="input_btn fr" name="" value="搜索">
    </div>
    <div class="guest_cart fr">
        <a href="{% url 'main:cart' %}" class="cart_name fl">我的购物车</a>
        <div class="goods_count fl" id="show_count">1</div>
    </div>
</div>
    <div class="navbar_con">
        <div class="navbar">
            <h1 class="fl">全部商品分类</h1>
            <ul class="navlist fl">
                <li><a href="">首页</a></li>
                <li class="interval">|</li>
                <li><a href="">手机生鲜</a></li>
                <li class="interval">|</li>
                <li><a href="">抽奖</a></li>
            </ul>
        </div>
    </div>
    <div class="center_con clearfix">
        <ul class="subnav fl">
            <li><a href="#model01" class="fruit">新鲜水果</a></li>
            <li><a href="#model02" class="seafood">海鲜水产</a></li>
            {#            <li><a href="#model03" class="meet">猪牛羊肉</a></li>#}
            {#            <li><a href="#model04" class="egg">禽类蛋品</a></li>#}
            {#            <li><a href="#model05" class="vegetables">新鲜蔬菜</a></li>#}
            {#            <li><a href="#model06" class="ice">速冻食品</a></li>#}
        </ul>
        <div class="slide fl">
            <ul class="slide_pics">
                <li><img src="/static/images/slide.jpg" alt="幻灯片"></li>
                <li><img src="/static/images/slide02.jpg" alt="幻灯片"></li>
                <li><img src="/static/images/slide03.jpg" alt="幻灯片"></li>
                <li><img src="/static/images/slide04.jpg" alt="幻灯片"></li>
            </ul>
            <div class="prev"></div>
            <div class="next"></div>
            <ul class="points"></ul>
        </div>
        <div class="adv fl">
            <a href="#"><img src="/static/images/adv01.jpg"></a>
            <a href="#"><img src="/static/images/adv02.jpg"></a>
        </div>
    </div>

    <div class="list_model">
        <div class="list_title clearfix">
            <h3 class="fl" id="model01">新鲜水果</h3>
            <div class="subtitle fl">
                <span>|</span>
                <a href="#">鲜芒</a>
                <a href="#">加州提子</a>
                <a href="#">亚马逊牛油果</a>
            </div>
            <a href="{% url 'main:list' 3 1 %}" class="goods_more fr" id="fruit_more">查看更多></a>
        </div>

        <div class="goods_con clearfix">
            <div class="goods_banner fl"><img src="/static/images/banner01.jpg"></div>
            <ul class="goods_list fl">
                {% for p in pic %}
                    <li>
                        <h4><a href="#">{{ p.gtitle }}</a></h4>
                        <a href="{% url 'main:detail' p.id %}">{{ p.gpic|safe }}</a>
                        <div class="prize">¥{{ p.gprice }}</div>
                    </li>

                {% endfor %}

            </ul>
        </div>
    </div>

    <div class="list_model">
        <div class="list_title clearfix">
            <h3 class="fl" id="model02">海鲜水产</h3>
            <div class="subtitle fl">
                <span>|</span>
                <a href="#">河虾</a>
                <a href="#">扇贝</a>
            </div>
           # <a href="{% url 'main:list' 4 1 %}" class="goods_more fr">查看更多 ></a>
        </div>

        <div class="goods_con clearfix">
            <div class="goods_banner fl"><img src="/static/images/banner02.jpg"></div>
            <ul class="goods_list fl">
                {% for foo in pic2 %}
                    <li>
                        <h4><a href="#">{{ foo.gtitle }}</a></h4>
                        <a href="{% url 'main:detail' foo.id %}">{{ foo.gpic|safe }}</a>
                        <div class="prize">¥{{ foo.gprice }}</div>
                    </li>

                {% endfor %}

            </ul>
        </div>
    </div>

    {#    <div class="list_model">#}
    {#        <div class="list_title clearfix">#}
    {#            <h3 class="fl" id="model03">猪牛羊肉</h3>#}
    {#            <div class="subtitle fl">#}
    {#                <span>|</span>#}
    {#                <a href="#">鲜芒</a>#}
    {#                <a href="#">加州提子</a>#}
    {#                <a href="#">亚马逊牛油果</a>#}
    {#            </div>#}
    {#            <a href="#" class="goods_more fr">查看更多 ></a>#}
    {#        </div>#}
    {##}
    {#        <div class="goods_con clearfix">#}
    {#            <div class="goods_banner fl"><img src="/static/images/banner03.jpg"></div>#}
    {#            <ul class="goods_list fl">#}
    {#                <li>#}
    {#                    <h4><a href="#">维多利亚葡萄维多利亚葡萄维多利亚葡萄维多利亚葡萄</a></h4>#}
    {#                    <a href="#"><img src="/static/images/goods.jpg"></a>#}
    {#                    <div class="prize">¥ 38.00</div>#}
    {#                </li>#}
    {#                <li>#}
    {#                    <h4><a href="#">维多利亚葡萄</a></h4>#}
    {#                    <a href="#"><img src="/static/images/goods.jpg"></a>#}
    {#                    <div class="prize">¥ 38.00</div>#}
    {#                </li>#}
    {#                <li>#}
    {#                    <h4><a href="#">维多利亚葡萄</a></h4>#}
    {#                    <a href="#"><img src="/static/images/goods.jpg"></a>#}
    {#                    <div class="prize">¥ 38.00</div>#}
    {#                </li>#}
    {#                <li>#}
    {#                    <h4><a href="#">维多利亚葡萄</a></h4>#}
    {#                    <a href="#"><img src="/static/images/goods.jpg"></a>#}
    {#                    <div class="prize">¥ 38.00</div>#}
    {#                </li>#}
    {#            </ul>#}
    {#        </div>#}
    {#    </div>#}
    {##}
    {#    <div class="list_model">#}
    {#        <div class="list_title clearfix">#}
    {#            <h3 class="fl" id="model04">禽类蛋品</h3>#}
    {#            <div class="subtitle fl">#}
    {#                <span>|</span>#}
    {#                <a href="#">鲜芒</a>#}
    {#                <a href="#">加州提子</a>#}
    {#                <a href="#">亚马逊牛油果</a>#}
    {#            </div>#}
    {#            <a href="#" class="goods_more fr">查看更多 ></a>#}
    {#        </div>#}
    {##}
    {#        <div class="goods_con clearfix">#}
    {#            <div class="goods_banner fl"><img src="/static/images/banner04.jpg"></div>#}
    {#            <ul class="goods_list fl">#}
    {#                <li>#}
    {#                    <h4><a href="#">维多利亚葡萄维多利亚葡萄维多利亚葡萄维多利亚葡萄</a></h4>#}
    {#                    <a href="#"><img src="/static/images/goods.jpg"></a>#}
    {#                    <div class="prize">¥ 38.00</div>#}
    {#                </li>#}
    {#                <li>#}
    {#                    <h4><a href="#">维多利亚葡萄</a></h4>#}
    {#                    <a href="#"><img src="/static/images/goods.jpg"></a>#}
    {#                    <div class="prize">¥ 38.00</div>#}
    {#                </li>#}
    {#                <li>#}
    {#                    <h4><a href="#">维多利亚葡萄</a></h4>#}
    {#                    <a href="#"><img src="/static/images/goods.jpg"></a>#}
    {#                    <div class="prize">¥ 38.00</div>#}
    {#                </li>#}
    {#                <li>#}
    {#                    <h4><a href="#">维多利亚葡萄</a></h4>#}
    {#                    <a href="#"><img src="/static/images/goods.jpg"></a>#}
    {#                    <div class="prize">¥ 38.00</div>#}
    {#                </li>#}
    {#            </ul>#}
    {#        </div>#}
    {#    </div>#}
    {##}
    {#    <div class="list_model">#}
    {#        <div class="list_title clearfix">#}
    {#            <h3 class="fl" id="model05">新鲜蔬菜</h3>#}
    {#            <div class="subtitle fl">#}
    {#                <span>|</span>#}
    {#                <a href="#">鲜芒</a>#}
    {#                <a href="#">加州提子</a>#}
    {#                <a href="#">亚马逊牛油果</a>#}
    {#            </div>#}
    {#            <a href="#" class="goods_more fr">查看更多 ></a>#}
    {#        </div>#}
    {##}
    {#        <div class="goods_con clearfix">#}
    {#            <div class="goods_banner fl"><img src="/static/images/banner05.jpg"></div>#}
    {#            <ul class="goods_list fl">#}
    {#                <li>#}
    {#                    <h4><a href="#">维多利亚葡萄维多利亚葡萄维多利亚葡萄维多利亚葡萄</a></h4>#}
    {#                    <a href="#"><img src="/static/images/goods.jpg"></a>#}
    {#                    <div class="prize">¥ 38.00</div>#}
    {#                </li>#}
    {#                <li>#}
    {#                    <h4><a href="#">维多利亚葡萄</a></h4>#}
    {#                    <a href="#"><img src="/static/images/goods.jpg"></a>#}
    {#                    <div class="prize">¥ 38.00</div>#}
    {#                </li>#}
    {#                <li>#}
    {#                    <h4><a href="#">维多利亚葡萄</a></h4>#}
    {#                    <a href="#"><img src="/static/images/goods.jpg"></a>#}
    {#                    <div class="prize">¥ 38.00</div>#}
    {#                </li>#}
    {#                <li>#}
    {#                    <h4><a href="#">维多利亚葡萄</a></h4>#}
    {#                    <a href="#"><img src="/static/images/goods.jpg"></a>#}
    {#                    <div class="prize">¥ 38.00</div>#}
    {#                </li>#}
    {#            </ul>#}
    {#        </div>#}
    {#    </div>#}
    {##}
    {#    <div class="list_model">#}
    {#        <div class="list_title clearfix">#}
    {#            <h3 class="fl" id="model06">速冻食品</h3>#}
    {#            <div class="subtitle fl">#}
    {#                <span>|</span>#}
    {#                <a href="#">鲜芒</a>#}
    {#                <a href="#">加州提子</a>#}
    {#                <a href="#">亚马逊牛油果</a>#}
    {#            </div>#}
    {#            <a href="#" class="goods_more fr">查看更多 ></a>#}
    {#        </div>#}
    {##}
    {#        <div class="goods_con clearfix">#}
    {#            <div class="goods_banner fl"><img src="/static/images/banner06.jpg"></div>#}
    {#            <ul class="goods_list fl">#}
    {#                <li>#}
    {#                    <h4><a href="#">维多利亚葡萄维多利亚葡萄维多利亚葡萄维多利亚葡萄</a></h4>#}
    {#                    <a href="#"><img src="/static/images/goods.jpg"></a>#}
    {#                    <div class="prize">¥ 38.00</div>#}
    {#                </li>#}
    {#                <li>#}
    {#                    <h4><a href="#">维多利亚葡萄</a></h4>#}
    {#                    <a href="#"><img src="/static/images/goods.jpg"></a>#}
    {#                    <div class="prize">¥ 38.00</div>#}
    {#                </li>#}
    {#                <li>#}
    {#                    <h4><a href="#">维多利亚葡萄</a></h4>#}
    {#                    <a href="#"><img src="/static/images/goods.jpg"></a>#}
    {#                    <div class="prize">¥ 38.00</div>#}
    {#                </li>#}
    {#                <li>#}
    {#                    <h4><a href="#">维多利亚葡萄</a></h4>#}
    {#                    <a href="#"><img src="/static/images/goods.jpg"></a>#}
    {#                    <div class="prize">¥ 38.00</div>#}
    {#                </li>#}
    {#            </ul>#}
    {#        </div>#}
    {#    </div>#}
{% endblock %}




Leong_Project/templates/list.html
{% extends 'base2.html' %}
{% block title %}乐农优选-商品列表{% endblock %}

<body>
{% block body %}
    <div class="search_bar clearfix">
    <a href="index.html" class="logo fl"><img src="/static/images/logo.png"></a>
    <div class="search_con fl">
        <input type="text" class="input_text fl" name="" placeholder="搜索商品">
        <input type="button" class="input_btn fr" name="" value="搜索">
    </div>
    <div class="guest_cart fr">
        <a href="{% url 'main:cart' %}" class="cart_name fl">我的购物车</a>
        <div class="goods_count fl" id="show_count">1</div>
    </div>
</div>
    <div class="navbar_con">
        <div class="navbar clearfix">
            <div class="subnav_con fl">
                <h1>全部商品分类</h1>
                <span></span>
                <ul class="subnav">
                    <li><a href="{% url 'main:list' 3 1 %}" class="fruit">新鲜水果</a></li>
                    <li><a href="{% url 'main:list' 4 1 %}" class="seafood">海鲜水产</a></li>
                    <li><a href="#" class="meet">猪牛羊肉</a></li>
                    <li><a href="#" class="egg">禽类蛋品</a></li>
                    <li><a href="#" class="vegetables">新鲜蔬菜</a></li>
                    <li><a href="#" class="ice">速冻食品</a></li>
                </ul>
            </div>
            <ul class="navlist fl">
                <li><a href="{% url 'main:index' %}">首页</a></li>
                <li class="interval">|</li>
                <li><a href="">手机生鲜</a></li>
                <li class="interval">|</li>
                <li><a href="">抽奖</a></li>
            </ul>
        </div>
    </div>

    <div class="breadcrumb">
        <a href="#">全部分类</a>
        <span>></span>
        <a href="#">新鲜水果</a>
    </div>

    <div class="main_wrap clearfix">
        <div class="l_wrap fl clearfix">
            <div class="new_goods">
                <h3>新品推荐</h3>
                <ul>
                    <li>
                        <a href="#"><img src="/static/images/goods/goods001.jpg"></a>
                        <h4><a href="#">进口柠檬</a></h4>
                        <div class="prize">￥3.90</div>
                    </li>
                    <li>
                        <a href="#"><img src="/static/images/goods/goods002.jpg"></a>
                        <h4><a href="#">玫瑰香葡萄</a></h4>
                        <div class="prize">￥16.80</div>
                    </li>
                </ul>
            </div>
        </div>

        <div class="r_wrap fr clearfix">
            <div class="sort_bar">
                <a href="#" class="active">默认</a>
                <a href="#">价格</a>
                <a href="#">人气</a>
            </div>

            <ul class="goods_type_list clearfix">
                {% for a in p %}
                    <li>
                        <a href="#">{{ a.gpic|safe }}</a>
                        <h4><a href="{% url 'main:detail' a.id %}">{{ a.gtitle }}</a></h4>
                        <div class="operate">
                            <span class="prize">￥{{ a.gprice }}</span>
                            <span class="unit">{{ a.gunit }}</span>
                            <a href="#" class="add_goods" title="加入购物车"></a>
                        </div>
                    </li>

                {% endfor %}


            </ul>

            <div class="pagenation">
                <a href="#">上一页</a>
                {% for i in p.paginator.page_range %}
                    <a href="{% url 'main:list' gtype_id i %}">{{ i }}</a>
                {% endfor %}
                <a href="#">下一页></a>
            </div>
        </div>
    </div>
{% endblock %}
</body>

	


Leong_Project/templates/login.html
{% extends 'base.html' %}
{% block title %}登录{% endblock %}
{% block head %}
    <script type="text/javascript" src="/static/js/jquery-1.12.4.min.js"></script>
{% endblock %}

{% block body %}
    <div class="login_top clearfix">
        <a href="index.html" class="login_logo"><img src="/static/images/logo02.png"></a>
    </div>

    <div class="login_form_bg">
        <div class="login_form_wrap clearfix">
            <div class="login_banner fl"></div>
            <div class="slogan fl">日夜兼程 · 急速送达</div>
            <div class="login_form fr">
                <div class="login_title clearfix">
                    <h1>用户登录</h1>
                    <a href="{% url 'user:register' %}">立即注册</a>
                </div>
                <div class="form_input">
                    <form action="{% url 'user:loginhandle' %}" method="post">
                        {% csrf_token %}
                        <input type="text" name="username" class="name_input" placeholder="请输入用户名">
                        <div class="user_error">输入错误</div>
                        <input type="password" name="pwd" class="pass_input" placeholder="请输入密码">
                        <div class="pwd_error">输入错误</div>
                        <div class="more_input clearfix">
                            <input type="checkbox" name="">
                            <label>记住用户名</label>
                            <a href="#">忘记密码</a>
                        </div>
                        <input type="submit" name="" value="登录" class="input_submit">
                    </form>
                </div>
            </div>
        </div>
    </div>
{% endblock %}


Leong_Project/templates/register.html
{% extends 'base.html' %}
{% block title %}注册{% endblock %}
{% block head %}
    <script type="text/javascript" src="/static/js/register.js"></script>
{% endblock %}

{% block body %}
    <div class="register_con">
        <div class="l_con fl">
            <a class="reg_logo"><img src="/static/images/logo02.png"></a>
            <div class="reg_slogan">足不出户 · 新鲜每一天</div>
            <div class="reg_banner"></div>
        </div>

        <div class="r_con fr">
            <div class="reg_title clearfix">
                <h1>用户注册</h1>
                <a href="{% url 'user:login' %}">登录</a>
            </div>
            <div class="reg_form clearfix">
                <form action="{% url 'user:register_handle' %}" method="post">
                    {% csrf_token %}
                    <ul>
                        <li>
                            <label>用户名:</label>
                            <input type="text" name="user_name" id="user_name">
                            <span class="error_tip">提示信息</span>
                        </li>
                        <li>
                            <label>密码:</label>
                            <input type="password" name="pwd" id="pwd">
                            <span class="error_tip">提示信息</span>
                        </li>
                        <li>
                            <label>确认密码:</label>
                            <input type="password" name="cpwd" id="cpwd">
                            <span class="error_tip">提示信息</span>
                        </li>
                        <li>
                            <label>邮箱:</label>
                            <input type="text" name="email" id="email">
                            <span class="error_tip">提示信息</span>
                        </li>
                        <li class="agreement">
                            <input type="checkbox" name="allow" id="allow" checked="checked">
                            <label>同意”天天生鲜用户使用协议“</label>
                            <span class="error_tip2">提示信息</span>
                        </li>
                        <li class="reg_sub">
                            <input type="submit" value="注 册" name="">
                        </li>
                    </ul>
                </form>
            </div>

        </div>

    </div>
{% endblock %}



	
