state_maintain/test1/urls.py
from django.conf.urls import url
from . import views

urlpatterns = [
    url(r'^index/',views.index,name='index'),
    url(r'^login/',views.login,name='login'),
    url(r'^loginhandle',views.loginhandle,name='loginhandle'),
    url(r'^logout/',views.logout,name='logout')
]

state_maintain/zhungtaibaochi/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from test1 import urls
urlpatterns = [
    url(r'^admin/', include(admin.site.urls)),
    url(r'^',include(urls,namespace='main'))
]

state_maintain/test1/views.py
from django.shortcuts import render, redirect


# Create your views here.
def index(request):
    if request.session.get('uname') is not None:
        uname = request.session.get('uname')
    else:
        uname = '未登录'
    return render(request, 'index.html', {'uname': uname})


def login(request):
    return render(request, 'login.html')


def loginhandle(request):
    request.session['uname'] = request.POST['uname']
    return redirect('main:index')


def logout(request):
    del request.session['uname']
    return redirect('main:index')

state_maintain/templates/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
<h3>hello,world{{ uname }}</h3>
<a href="{% url 'main:login' %}">登录</a>
<br>
<a href="{% url 'main:logout' %}">退出</a>
</body>
</html>

state_maintain/templates/login.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>登录</title>
</head>
<body>
<form action="{% url 'main:loginhandle' %}" method="post">
    {% csrf_token %}
    用户名：<input type="text" name="uname">
    <br>
    <input type="submit" value="登录">
</form>
</body>
</html>